id: P000507
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG15521
  title: གྲངས་རིག་བསམ་བློའི་ཐབས་ལམ་རྣམ་བཤད།
  author: ''
  volumes:
    71e3924db3a740c6bb065e21f6ebbb34:
      image_group_id: I1KG15841
      title: Volume 1 of grangs rig bsam blo'i thabs lam rnam bshad/
      volume_number: 1
      total_pages: 236
      base_file: v001.txt
